title: Blood Moon's Gaze
description: Fantasy RPG Wiki for bronze age inspired gaming.
remote_theme: just-the-docs/just-the-docs

url: https://JumaJuiceTime.github.io/BloodMoonsGaze

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
